# Generated by OmopViewer 0.3.0
# Be careful editing this file

library(bslib)
library(cli)
library(CohortCharacteristics)
library(DiagrammeR)
library(DiagrammeRsvg)
library(dplyr)
library(DrugUtilisation)
library(DT)
library(ggplot2)
library(gt)
library(IncidencePrevalence)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(plotly)
library(purrr)
library(reactable)
library(readr)
library(rlang)
library(rsvg)
library(shiny)
library(shinycssloaders)
library(shinyTree)
library(shinyWidgets)
library(sortable)
library(stringr)
library(tidyr)
library(visOmopResults)
library(yaml)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "shinyData.RData")
if (!file.exists(fileData)) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "data"))

# load shiny data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))

theme_set(
  theme_grey(base_size = 16) +  # Set reasonable default size
    theme(
      axis.text.y = element_text(size = 15),        # smaller y-axis labels
      strip.text = element_text(size = 15),         # facet label
      legend.text = element_text(size = 10),        # legend text
      legend.title = element_text(size = 10),
      axis.title = element_text(size = 12)
    )
)
