# Generated by OmopViewer 0.3.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # summarise_omop_snapshot -----
  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::reactive({
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTidy <- shiny::reactive({
    tidyDT(getSummariseOmopSnapshotData(), input$summarise_omop_snapshot_tidy_columns, input$summarise_omop_snapshot_tidy_pivot_estimates)
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    getSummariseOmopSnapshotTidy()
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseOmopSnapshotData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_cohort_count -----
  ## get summarise_cohort_count data
  getSummariseCohortCountData <- shiny::reactive({
    data[["summarise_cohort_count"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_count_cdm_name,
        .data$variable_name %in% input$summarise_cohort_count_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_count_cohort_name) |>
      omopgenerics::filterSettings(.data$table_name %in% input$summarise_cohort_count_table_name)
  })
  getSummariseCohortCountTidy <- shiny::reactive({
    tidyDT(getSummariseCohortCountData(), input$summarise_cohort_count_tidy_columns, input$summarise_cohort_count_tidy_pivot_estimates)
  })
  output$summarise_cohort_count_tidy <- DT::renderDT({
    getSummariseCohortCountTidy()
  })
  output$summarise_cohort_count_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCohortCountData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCohortCountTable <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::tableCohortCount(
        header = input$summarise_cohort_count_table_header,
        groupColumn = input$summarise_cohort_count_table_group_column,
        hide = input$summarise_cohort_count_table_hide
      )
  })
  output$summarise_cohort_count_table <- gt::render_gt({
    getSummariseCohortCountTable()
  })
  output$summarise_cohort_count_table_download <- shiny::downloadHandler(
    filename = paste0("table_count.", input$summarise_cohort_count_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortCountTable(), file)
    }
  )
  getSummariseCohortCountPlot <- shiny::reactive({
    getSummariseCohortCountData() |>
      CohortCharacteristics::plotCohortCount(
        facet = input$summarise_cohort_count_plot_facet,
        colour = input$summarise_cohort_count_plot_colour
      )
  })
  output$summarise_cohort_count_plot <- shiny::renderPlot({
    getSummariseCohortCountPlot()
  })
  output$summarise_cohort_count_plot_download <- shiny::downloadHandler(
    filename = "plot_count.png",
    content = function(file) {
      plt <- getSummariseCohortCountPlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$summarise_cohort_count_plot_width),
        height = as.numeric(input$summarise_cohort_count_plot_height),
        units = input$summarise_cohort_count_plot_units,
        dpi = as.numeric(input$summarise_cohort_count_plot_dpi)
      )
    }
  )
  # summarise_cohort_attrition -----
  ## get summarise_cohort_attrition data
  getSummariseCohortAttritionData <- shiny::reactive({
    data[["summarise_cohort_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_cohort_attrition_cdm_name,
        .data$variable_name %in% input$summarise_cohort_attrition_variable_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_cohort_attrition_cohort_name)
  })
  getSummariseCohortAttritionTidy <- shiny::reactive({
    tidyDT(getSummariseCohortAttritionData(), input$summarise_cohort_attrition_tidy_columns, input$summarise_cohort_attrition_tidy_pivot_estimates)
  })
  output$summarise_cohort_attrition_tidy <- DT::renderDT({
    getSummariseCohortAttritionTidy()
  })
  output$summarise_cohort_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCohortAttritionData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCohortAttritionTable <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::tableCohortAttrition(
        header = input$summarise_cohort_attrition_table_header,
        groupColumn = input$summarise_cohort_attrition_table_group_column,
        hide = input$summarise_cohort_attrition_table_hide
      )
  })
  output$summarise_cohort_attrition_table <- gt::render_gt({
    getSummariseCohortAttritionTable()
  })
  output$summarise_cohort_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_attrition.", input$summarise_cohort_attrition_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCohortAttritionTable(), file)
    }
  )
  getSummariseCohortAttritionDiagram <- shiny::reactive({
    getSummariseCohortAttritionData() |>
      CohortCharacteristics::plotCohortAttrition(
        show = input$summarise_cohort_attrition_diagram_show
      )
  })
  output$summarise_cohort_attrition_diagram <- DiagrammeR::renderGrViz({
    getSummariseCohortAttritionDiagram()
  })
  output$summarise_cohort_attrition_diagram_download <- shiny::downloadHandler(
    filename = "attrition_diagram.png",
    content = function(file) {
      svg <- DiagrammeRsvg::export_svg(getSummariseCohortAttritionDiagram())
      rsvg::rsvg_png(charToRaw(svg), file, width = input$summarise_cohort_attrition_diagram_width)
    }
  )
  # summarise_characteristics -----
  ## get summarise_characteristics data
  getSummariseCharacteristicsData <- shiny::reactive({
    data[["summarise_characteristics"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_characteristics_cdm_name,
        .data$variable_name %in% input$summarise_characteristics_variable_name,
        .data$estimate_name %in% input$summarise_characteristics_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_characteristics_cohort_name) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_characteristics_age_group,
        .data$sex %in% input$summarise_characteristics_sex
      )
  })
  getSummariseCharacteristicsTidy <- shiny::reactive({
    tidyDT(getSummariseCharacteristicsData(), input$summarise_characteristics_tidy_columns, input$summarise_characteristics_tidy_pivot_estimates)
  })
  output$summarise_characteristics_tidy <- DT::renderDT({
    getSummariseCharacteristicsTidy()
  })
  output$summarise_characteristics_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseCharacteristicsData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseCharacteristicsTable <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::tableCharacteristics(
        header = input$summarise_characteristics_table_header,
        groupColumn = input$summarise_characteristics_table_group_column,
        hide = input$summarise_characteristics_table_hide
      )
  })
  output$summarise_characteristics_table <- gt::render_gt({
    getSummariseCharacteristicsTable()
  })
  output$summarise_characteristics_table_download <- shiny::downloadHandler(
    filename = paste0("table_characteristics.", input$summarise_characteristics_table_format),
    content = function(file) {
      gt::gtsave(getSummariseCharacteristicsTable(), file)
    }
  )
  getSummariseCharacteristicsPlot <- shiny::reactive({
    getSummariseCharacteristicsData() |>
      CohortCharacteristics::plotCharacteristics(
        plotType = input$summarise_characteristics_plot_plot_type,
        facet = input$summarise_characteristics_plot_facet,
        colour = input$summarise_characteristics_plot_colour
      )
  })
  output$summarise_characteristics_plot <- shiny::renderPlot({
    getSummariseCharacteristicsPlot()
  })
  output$summarise_characteristics_plot_download <- shiny::downloadHandler(
    filename = "plot_characteristics.png",
    content = function(file) {
      plt <- getSummariseCharacteristicsPlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$summarise_characteristics_plot_width),
        height = as.numeric(input$summarise_characteristics_plot_height),
        units = input$summarise_characteristics_plot_units,
        dpi = as.numeric(input$summarise_characteristics_plot_dpi)
      )
    }
  )
  # incidence -----
  ## get incidence data
  getIncidenceData <- shiny::reactive({
    data[["incidence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_cdm_name,
        .data$variable_name %in% input$incidence_variable_name,
        .data$estimate_name %in% input$incidence_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$incidence_outcome_cohort_name) |>
      omopgenerics::filterAdditional(
        .data$incidence_start_date %in% input$incidence_incidence_start_date,
        .data$analysis_interval %in% input$incidence_analysis_interval
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_censor_cohort_name %in% input$incidence_analysis_censor_cohort_name,
        .data$analysis_complete_database_intervals %in% input$incidence_analysis_complete_database_intervals,
        .data$analysis_outcome_washout %in% input$incidence_analysis_outcome_washout,
        .data$analysis_repeated_events %in% input$incidence_analysis_repeated_events,
        .data$denominator_age_group %in% input$incidence_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$incidence_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$incidence_denominator_end_date,
        .data$denominator_requirements_at_entry %in% input$incidence_denominator_requirements_at_entry,
        .data$denominator_sex %in% input$incidence_denominator_sex,
        .data$denominator_start_date %in% input$incidence_denominator_start_date,
        .data$denominator_target_cohort_name %in% input$incidence_denominator_target_cohort_name,
        .data$denominator_time_at_risk %in% input$incidence_denominator_time_at_risk
      )
  })
  getIncidenceTidy <- shiny::reactive({
    tidyDT(getIncidenceData(), input$incidence_tidy_columns, input$incidence_tidy_pivot_estimates)
  })
  output$incidence_tidy <- DT::renderDT({
    getIncidenceTidy()
  })
  output$incidence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getIncidenceData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getIncidenceTable <- shiny::reactive({
    res <- getIncidenceData()
    res |>
      IncidencePrevalence::tableIncidence(
        header = input$incidence_table_header,
        groupColumn = input$incidence_table_group_column,
        hide = input$incidence_table_hide,
        settingsColumn = omopgenerics::settingsColumns(res)
      )
  })
  output$incidence_table <- gt::render_gt({
    getIncidenceTable()
  })
  output$incidence_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence.", input$incidence_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceTable(), file)
    }
  )
  getIncidencePlot <- shiny::reactive({
    getIncidenceData() |>
      IncidencePrevalence::plotIncidence(
        x = input$incidence_plot_x,
        facet = input$incidence_plot_facet,
        colour = input$incidence_plot_colour
      )
  })
  output$incidence_plot <- shiny::renderPlot({
    getIncidencePlot()
  })
  output$incidence_plot_download <- shiny::downloadHandler(
    filename = "plot_incidence.png",
    content = function(file) {
      plt <- getIncidencePlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$incidence_plot_width),
        height = as.numeric(input$incidence_plot_height),
        units = input$incidence_plot_units,
        dpi = as.numeric(input$incidence_plot_dpi)
      )
    }
  )
  # incidence_attrition -----
  ## get incidence_attrition data
  getIncidenceAttritionData <- shiny::reactive({
    data[["incidence_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$incidence_attrition_cdm_name,
        .data$variable_name %in% input$incidence_attrition_variable_name
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_censor_cohort_name %in% input$incidence_attrition_analysis_censor_cohort_name,
        .data$analysis_complete_database_intervals %in% input$incidence_attrition_analysis_complete_database_intervals,
        .data$analysis_outcome_washout %in% input$incidence_attrition_analysis_outcome_washout,
        .data$analysis_repeated_events %in% input$incidence_attrition_analysis_repeated_events,
        .data$denominator_age_group %in% input$incidence_attrition_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$incidence_attrition_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$incidence_attrition_denominator_end_date,
        .data$denominator_requirements_at_entry %in% input$incidence_attrition_denominator_requirements_at_entry,
        .data$denominator_sex %in% input$incidence_attrition_denominator_sex,
        .data$denominator_start_date %in% input$incidence_attrition_denominator_start_date,
        .data$denominator_target_cohort_name %in% input$incidence_attrition_denominator_target_cohort_name,
        .data$denominator_time_at_risk %in% input$incidence_attrition_denominator_time_at_risk
      )
  })
  getIncidenceAttritionTidy <- shiny::reactive({
    tidyDT(getIncidenceAttritionData(), input$incidence_attrition_tidy_columns, input$incidence_attrition_tidy_pivot_estimates)
  })
  output$incidence_attrition_tidy <- DT::renderDT({
    getIncidenceAttritionTidy()
  })
  output$incidence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getIncidenceAttritionData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getIncidenceAttritionTable <- shiny::reactive({
    res <- getIncidenceAttritionData()
    res |>
      IncidencePrevalence::tableIncidenceAttrition(
        header = input$incidence_attrition_table_header,
        settingsColumn = omopgenerics::settingsColumns(res),
        groupColumn = input$incidence_attrition_table_group_column,
        hide = input$incidence_attrition_table_hide
      )
  })
  output$incidence_attrition_table <- gt::render_gt({
    getIncidenceAttritionTable()
  })
  output$incidence_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_incidence_attrition.", input$incidence_attrition_table_format),
    content = function(file) {
      gt::gtsave(getIncidenceAttritionTable(), file)
    }
  )
  # prevalence -----
  ## get prevalence data
  getPrevalenceData <- shiny::reactive({
    data[["prevalence"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$prevalence_cdm_name,
        .data$variable_name %in% input$prevalence_variable_name,
        .data$estimate_name %in% input$prevalence_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$outcome_cohort_name %in% input$prevalence_outcome_cohort_name) |>
      omopgenerics::filterAdditional(
        .data$prevalence_start_date %in% input$prevalence_prevalence_start_date,
        .data$prevalence_end_date %in% input$prevalence_prevalence_end_date,
        .data$analysis_interval %in% input$prevalence_analysis_interval
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_complete_database_intervals %in% input$prevalence_analysis_complete_database_intervals,
        .data$analysis_full_contribution %in% input$prevalence_analysis_full_contribution,
        .data$analysis_type %in% input$prevalence_analysis_type,
        .data$denominator_age_group %in% input$prevalence_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$prevalence_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$prevalence_denominator_end_date,
        .data$denominator_requirements_at_entry %in% input$prevalence_denominator_requirements_at_entry,
        .data$denominator_sex %in% input$prevalence_denominator_sex,
        .data$denominator_start_date %in% input$prevalence_denominator_start_date,
        .data$denominator_target_cohort_name %in% input$prevalence_denominator_target_cohort_name,
        .data$denominator_time_at_risk %in% input$prevalence_denominator_time_at_risk
      )
  })
  getPrevalenceTidy <- shiny::reactive({
    tidyDT(getPrevalenceData(), input$prevalence_tidy_columns, input$prevalence_tidy_pivot_estimates)
  })
  output$prevalence_tidy <- DT::renderDT({
    getPrevalenceTidy()
  })
  output$prevalence_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getPrevalenceData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getPrevalenceTable <- shiny::reactive({
    res <- getPrevalenceData()
    res |>
      IncidencePrevalence::tablePrevalence(
        header = input$prevalence_table_header,
        groupColumn = input$prevalence_table_group_column,
        hide = input$prevalence_table_hide,
        settingsColumn = omopgenerics::settingsColumns(res)
      )
  })
  output$prevalence_table <- gt::render_gt({
    getPrevalenceTable()
  })
  output$prevalence_table_download <- shiny::downloadHandler(
    filename = paste0("table_prevalence.", input$prevalence_table_format),
    content = function(file) {
      gt::gtsave(getPrevalenceTable(), file)
    }
  )
  getPrevalencePlot <- shiny::reactive({
    getPrevalenceData() |>
      IncidencePrevalence::plotPrevalence(
        x = input$prevalence_plot_x,
        facet = input$prevalence_plot_facet,
        colour = input$prevalence_plot_colour
      )
  })
  output$prevalence_plot <- shiny::renderPlot({
    getPrevalencePlot()
  })
  output$prevalence_plot_download <- shiny::downloadHandler(
    filename = "plot_prevalence.png",
    content = function(file) {
      plt <- getPrevalencePlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$prevalence_plot_width),
        height = as.numeric(input$prevalence_plot_height),
        units = input$prevalence_plot_units,
        dpi = as.numeric(input$prevalence_plot_dpi)
      )
    }
  )
  # prevalence_attrition -----
  ## get prevalence_attrition data
  getPrevalenceAttritionData <- shiny::reactive({
    data[["prevalence_attrition"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$prevalence_attrition_cdm_name,
        .data$variable_name %in% input$prevalence_attrition_variable_name
      ) |>
      omopgenerics::filterSettings(
        .data$analysis_complete_database_intervals %in% input$prevalence_attrition_analysis_complete_database_intervals,
        .data$analysis_full_contribution %in% input$prevalence_attrition_analysis_full_contribution,
        .data$analysis_type %in% input$prevalence_attrition_analysis_type,
        .data$denominator_age_group %in% input$prevalence_attrition_denominator_age_group,
        .data$denominator_days_prior_observation %in% input$prevalence_attrition_denominator_days_prior_observation,
        .data$denominator_end_date %in% input$prevalence_attrition_denominator_end_date,
        .data$denominator_requirements_at_entry %in% input$prevalence_attrition_denominator_requirements_at_entry,
        .data$denominator_sex %in% input$prevalence_attrition_denominator_sex,
        .data$denominator_start_date %in% input$prevalence_attrition_denominator_start_date,
        .data$denominator_target_cohort_name %in% input$prevalence_attrition_denominator_target_cohort_name,
        .data$denominator_time_at_risk %in% input$prevalence_attrition_denominator_time_at_risk
      )
  })
  getPrevalenceAttritionTidy <- shiny::reactive({
    tidyDT(getPrevalenceAttritionData(), input$prevalence_attrition_tidy_columns, input$prevalence_attrition_tidy_pivot_estimates)
  })
  output$prevalence_attrition_tidy <- DT::renderDT({
    getPrevalenceAttritionTidy()
  })
  output$prevalence_attrition_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getPrevalenceAttritionData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getPrevalenceAttritionTable <- shiny::reactive({
    res <- getPrevalenceAttritionData()
    res |>
      IncidencePrevalence::tablePrevalenceAttrition(
        header = input$prevalence_attrition_table_header,
        settingsColumn = omopgenerics::settingsColumns(res),
        groupColumn = input$prevalence_attrition_table_group_column,
        hide = input$prevalence_attrition_table_hide
      )
  })
  output$prevalence_attrition_table <- gt::render_gt({
    getPrevalenceAttritionTable()
  })
  output$prevalence_attrition_table_download <- shiny::downloadHandler(
    filename = paste0("table_prevalence_attrition.", input$prevalence_attrition_table_format),
    content = function(file) {
      gt::gtsave(getPrevalenceAttritionTable(), file)
    }
  )
  # summarise_proportion_of_patients_covered -----
  ## get summarise_proportion_of_patients_covered data
  getSummariseProportionOfPatientsCoveredData <- shiny::reactive({
    data[["summarise_proportion_of_patients_covered"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_proportion_of_patients_covered_cdm_name,
        .data$estimate_name %in% input$summarise_proportion_of_patients_covered_estimate_name
      ) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_proportion_of_patients_covered_age_group,
        .data$sex %in% input$summarise_proportion_of_patients_covered_sex
      )
  })
  getSummariseProportionOfPatientsCoveredTidy <- shiny::reactive({
    tidyDT(getSummariseProportionOfPatientsCoveredData(), input$summarise_proportion_of_patients_covered_tidy_columns, input$summarise_proportion_of_patients_covered_tidy_pivot_estimates)
  })
  output$summarise_proportion_of_patients_covered_tidy <- DT::renderDT({
    getSummariseProportionOfPatientsCoveredTidy()
  })
  output$summarise_proportion_of_patients_covered_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseProportionOfPatientsCoveredData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseProportionOfPatientsCoveredTable <- shiny::reactive({
    getSummariseProportionOfPatientsCoveredData() |>
      DrugUtilisation::tableProportionOfPatientsCovered(
        header = input$summarise_proportion_of_patients_covered_table_header,
        groupColumn = input$summarise_proportion_of_patients_covered_table_group_column,
        hide = input$summarise_proportion_of_patients_covered_table_hide
      )
  })
  output$summarise_proportion_of_patients_covered_table <- gt::render_gt({
    getSummariseProportionOfPatientsCoveredTable()
  })
  output$summarise_proportion_of_patients_covered_table_download <- shiny::downloadHandler(
    filename = paste0("table_ppc.", input$summarise_proportion_of_patients_covered_table_format),
    content = function(file) {
      gt::gtsave(getSummariseProportionOfPatientsCoveredTable(), file)
    }
  )
  getSummariseProportionOfPatientsCoveredPlot <- shiny::reactive({
    getSummariseProportionOfPatientsCoveredData() |>
      DrugUtilisation::plotProportionOfPatientsCovered(
        ribbon = input$summarise_proportion_of_patients_covered_plot_ribbon,
        facet = input$summarise_proportion_of_patients_covered_plot_facet,
        colour = input$summarise_proportion_of_patients_covered_plot_colour
      )
  })
  output$summarise_proportion_of_patients_covered_plot <- shiny::renderPlot({
    getSummariseProportionOfPatientsCoveredPlot()
  })
  output$summarise_proportion_of_patients_covered_plot_download <- shiny::downloadHandler(
    filename = "plot_ppc.png",
    content = function(file) {
      plt <- getSummariseProportionOfPatientsCoveredPlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$summarise_proportion_of_patients_covered_plot_width),
        height = as.numeric(input$summarise_proportion_of_patients_covered_plot_height),
        units = input$summarise_proportion_of_patients_covered_plot_units,
        dpi = as.numeric(input$summarise_proportion_of_patients_covered_plot_dpi)
      )
    }
  )
  # summarise_drug_restart -----
  ## get summarise_drug_restart data
  getSummariseDrugRestartData <- shiny::reactive({
    data[["summarise_drug_restart"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_drug_restart_cdm_name,
        .data$estimate_name %in% input$summarise_drug_restart_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$cohort_name %in% input$summarise_drug_restart_cohort_name) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_drug_restart_age_group,
        .data$sex %in% input$summarise_drug_restart_sex
      )
  })
  getSummariseDrugRestartTidy <- shiny::reactive({
    tidyDT(getSummariseDrugRestartData(), input$summarise_drug_restart_tidy_columns, input$summarise_drug_restart_tidy_pivot_estimates)
  })
  output$summarise_drug_restart_tidy <- DT::renderDT({
    getSummariseDrugRestartTidy()
  })
  output$summarise_drug_restart_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseDrugRestartData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseDrugRestartTable <- shiny::reactive({
    getSummariseDrugRestartData() |>
      DrugUtilisation::tableDrugRestart(
        header = input$summarise_drug_restart_table_header,
        groupColumn = input$summarise_drug_restart_table_group_column,
        hide = input$summarise_drug_restart_table_hide
      )
  })
  output$summarise_drug_restart_table <- gt::render_gt({
    getSummariseDrugRestartTable()
  })
  output$summarise_drug_restart_table_download <- shiny::downloadHandler(
    filename = paste0("table_drug_restart.", input$summarise_drug_restart_table_format),
    content = function(file) {
      gt::gtsave(getSummariseDrugRestartTable(), file)
    }
  )
  getSummariseDrugRestartPlot <- shiny::reactive({
    getSummariseDrugRestartData() |>
      DrugUtilisation::plotDrugRestart(
        facet = input$summarise_drug_restart_plot_facet,
        colour = input$summarise_drug_restart_plot_colour
      )
  })
  output$summarise_drug_restart_plot <- shiny::renderPlot({
    getSummariseDrugRestartPlot()
  })
  output$summarise_drug_restart_plot_download <- shiny::downloadHandler(
    filename = "plot_drug_restart.png",
    content = function(file) {
      plt <- getSummariseDrugRestartPlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$summarise_drug_restart_plot_width),
        height = as.numeric(input$summarise_drug_restart_plot_height),
        units = input$summarise_drug_restart_plot_units,
        dpi = as.numeric(input$summarise_drug_restart_plot_dpi)
      )
    }
  )
  # summarise_drug_utilisation -----
  ## get summarise_drug_utilisation data
  getSummariseDrugUtilisationData <- shiny::reactive({
    data[["summarise_drug_utilisation"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_drug_utilisation_cdm_name,
        .data$variable_name %in% input$summarise_drug_utilisation_variable_name,
        .data$estimate_name %in% input$summarise_drug_utilisation_estimate_name
      ) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_drug_utilisation_age_group,
        .data$sex %in% input$summarise_drug_utilisation_sex
      ) |>
      omopgenerics::filterAdditional(
        .data$ingredient %in% input$summarise_drug_utilisation_ingredient,
        .data$concept_set %in% input$summarise_drug_utilisation_concept_set
      )
  })
  getSummariseDrugUtilisationTidy <- shiny::reactive({
    tidyDT(getSummariseDrugUtilisationData(), input$summarise_drug_utilisation_tidy_columns, input$summarise_drug_utilisation_tidy_pivot_estimates)
  })
  output$summarise_drug_utilisation_tidy <- DT::renderDT({
    getSummariseDrugUtilisationTidy()
  })
  output$summarise_drug_utilisation_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseDrugUtilisationData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseDrugUtilisationTable <- shiny::reactive({
    getSummariseDrugUtilisationData() |>
      DrugUtilisation::tableDrugUtilisation(
        header = input$summarise_drug_utilisation_table_header,
        groupColumn = input$summarise_drug_utilisation_table_group_column,
        hide = input$summarise_drug_utilisation_table_hide
      )
  })
  output$summarise_drug_utilisation_table <- gt::render_gt({
    getSummariseDrugUtilisationTable()
  })
  output$summarise_drug_utilisation_table_download <- shiny::downloadHandler(
    filename = paste0("table_drug_utilisation.", input$summarise_drug_utilisation_table_format),
    content = function(file) {
      gt::gtsave(getSummariseDrugUtilisationTable(), file)
    }
  )
  getSummariseDrugUtilisationPlot <- shiny::reactive({
    getSummariseDrugUtilisationData() |>
      DrugUtilisation::plotDrugUtilisation(
        variable = input$summarise_drug_utilisation_plot_variable,
        plotType = input$summarise_drug_utilisation_plot_plot_type,
        facet = input$summarise_drug_utilisation_plot_facet,
        colour = input$summarise_drug_utilisation_plot_colour
      )
  })
  
  getSummariseDrugUtilisationDensityData <- shiny::reactive({
    data[["summarise_drug_utilisation_density"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_drug_utilisation_cdm_name,
        .data$variable_name %in% input$summarise_drug_utilisation_variable_name
      ) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_drug_utilisation_age_group,
        .data$sex %in% input$summarise_drug_utilisation_sex
      ) |>
      omopgenerics::filterAdditional(
        .data$ingredient %in% input$summarise_drug_utilisation_ingredient
      )
  })
  
  getSummariseDrugUtilisationDesityPlot <- shiny::reactive({
    getSummariseDrugUtilisationDensityData() |>
      DrugUtilisation::plotDrugUtilisation(
        variable = input$summarise_drug_utilisation_density_plot_variable,
        plotType = input$summarise_drug_utilisation_density_plot_plot_type,
        facet = input$summarise_drug_utilisation_density_plot_facet,
        colour = input$summarise_drug_utilisation_density_plot_colour
      )
  })
  output$summarise_drug_utilisation_density_plot <-  shiny::renderPlot({
    getSummariseDrugUtilisationDesityPlot()
  })
  
  output$summarise_drug_utilisation_plot <- shiny::renderPlot({
    getSummariseDrugUtilisationPlot()
  })
  output$summarise_drug_utilisation_plot_download <- shiny::downloadHandler(
    filename = "plot_drug_utilisation.png",
    content = function(file) {
      plt <- getSummariseDrugUtilisationPlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$summarise_drug_utilisation_plot_width),
        height = as.numeric(input$summarise_drug_utilisation_plot_height),
        units = input$summarise_drug_utilisation_plot_units,
        dpi = as.numeric(input$summarise_drug_utilisation_plot_dpi)
      )
    }
  )
  # summarise_indication -----
  ## get summarise_indication data
  getSummariseIndicationData <- shiny::reactive({
    data[["summarise_indication"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_indication_cdm_name,
        .data$variable_name %in% input$summarise_indication_variable_name,
        .data$estimate_name %in% input$summarise_indication_estimate_name
      ) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_indication_age_group,
        .data$sex %in% input$summarise_indication_sex
      )
  })
  getSummariseIndicationTidy <- shiny::reactive({
    tidyDT(getSummariseIndicationData(), input$summarise_indication_tidy_columns, input$summarise_indication_tidy_pivot_estimates)
  })
  output$summarise_indication_tidy <- DT::renderDT({
    getSummariseIndicationTidy()
  })
  output$summarise_indication_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseIndicationData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseIndicationTable <- shiny::reactive({
    getSummariseIndicationData() |>
      DrugUtilisation::tableIndication(
        header = input$summarise_indication_table_header,
        groupColumn = input$summarise_indication_table_group_column,
        hide = input$summarise_indication_table_hide
      )
  })
  output$summarise_indication_table <- gt::render_gt({
    getSummariseIndicationTable()
  })
  output$summarise_indication_table_download <- shiny::downloadHandler(
    filename = paste0("table_indication.", input$summarise_indication_table_format),
    content = function(file) {
      gt::gtsave(getSummariseIndicationTable(), file)
    }
  )
  getSummariseIndicationPlot <- shiny::reactive({
    getSummariseIndicationData() |>
      DrugUtilisation::plotIndication(
        facet = input$summarise_indication_plot_facet,
      )
  })
  output$summarise_indication_plot <- shiny::renderPlot({
    getSummariseIndicationPlot()
  })
  output$summarise_indication_plot_download <- shiny::downloadHandler(
    filename = "plot_indication.png",
    content = function(file) {
      plt <- getSummariseIndicationPlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$summarise_indication_plot_width),
        height = as.numeric(input$summarise_indication_plot_height),
        units = input$summarise_indication_plot_units,
        dpi = as.numeric(input$summarise_indication_plot_dpi)
      )
    }
  )
  # summarise_treatment -----
  ## get summarise_treatment data
  getSummariseTreatmentData <- shiny::reactive({
    data[["summarise_treatment"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_treatment_cdm_name,
        .data$variable_name %in% input$summarise_treatment_variable_name,
        .data$estimate_name %in% input$summarise_treatment_estimate_name
      ) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_treatment_age_group,
        .data$sex %in% input$summarise_treatment_sex
      ) |>
      omopgenerics::filterSettings(
        .data$index_date %in% input$summarise_treatment_index_date
      )
  })
  getSummariseTreatmentTidy <- shiny::reactive({
    tidyDT(getSummariseTreatmentData(), input$summarise_treatment_tidy_columns, input$summarise_treatment_tidy_pivot_estimates)
  })
  output$summarise_treatment_tidy <- DT::renderDT({
    getSummariseTreatmentTidy()
  })
  output$summarise_treatment_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseTreatmentData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseTreatmentTable <- shiny::reactive({
    getSummariseTreatmentData() |>
      DrugUtilisation::tableTreatment(
        header = input$summarise_treatment_table_header,
        groupColumn = input$summarise_treatment_table_group_column,
        hide = input$summarise_treatment_table_hide
      )
  })
  output$summarise_treatment_table <- gt::render_gt({
    getSummariseTreatmentTable()
  })
  output$summarise_treatment_table_download <- shiny::downloadHandler(
    filename = paste0("table_treatment.", input$summarise_treatment_table_format),
    content = function(file) {
      gt::gtsave(getSummariseTreatmentTable(), file)
    }
  )
  getSummariseTreatmentPlot <- shiny::reactive({
    getSummariseTreatmentData() |>
      DrugUtilisation::plotTreatment(
        facet = input$summarise_treatment_plot_facet,
      )
  })
  output$summarise_treatment_plot <- shiny::renderPlot({
    getSummariseTreatmentPlot()
  })
  output$summarise_treatment_plot_download <- shiny::downloadHandler(
    filename = "plot_treatment.png",
    content = function(file) {
      plt <- getSummariseTreatmentPlot()
      ggplot2::ggsave(
        filename = file,
        plot = plt,
        width = as.numeric(input$summarise_treatment_plot_width),
        height = as.numeric(input$summarise_treatment_plot_height),
        units = input$summarise_treatment_plot_units,
        dpi = as.numeric(input$summarise_treatment_plot_dpi)
      )
    }
  )
  # benchmark_drug_utilisation -----
  ## get benchmark_drug_utilisation data
  getBenchmarkDrugUtilisationData <- shiny::reactive({
    data[["benchmark_drug_utilisation"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$benchmark_drug_utilisation_cdm_name,
        .data$variable_name %in% input$benchmark_drug_utilisation_variable_name,
        .data$estimate_name %in% input$benchmark_drug_utilisation_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$task %in% input$benchmark_drug_utilisation_task) |>
      omopgenerics::filterSettings(
        .data$alternative_ingredient %in% input$benchmark_drug_utilisation_alternative_ingredient,
        .data$ingredient %in% input$benchmark_drug_utilisation_ingredient,
        .data$person_n %in% input$benchmark_drug_utilisation_person_n,
        .data$source_type %in% input$benchmark_drug_utilisation_source_type
      )
  })
  getBenchmarkDrugUtilisationTidy <- shiny::reactive({
    tidyDT(getBenchmarkDrugUtilisationData(), input$benchmark_drug_utilisation_tidy_columns, input$benchmark_drug_utilisation_tidy_pivot_estimates)
  })
  output$benchmark_drug_utilisation_tidy <- DT::renderDT({
    getBenchmarkDrugUtilisationTidy()
  })
  output$benchmark_drug_utilisation_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getBenchmarkDrugUtilisationData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getBenchmarkDrugUtilisationTable <- shiny::reactive({
    getBenchmarkDrugUtilisationData() |>
      simpleTable(
        header = input$benchmark_drug_utilisation_table_header,
        group = input$benchmark_drug_utilisation_table_group_column,
        hide = input$benchmark_drug_utilisation_table_hide
      )
  })
  output$benchmark_drug_utilisation_table <- gt::render_gt({
    getBenchmarkDrugUtilisationTable()
  })
  output$benchmark_drug_utilisation_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$benchmark_drug_utilisation_table_format),
    content = function(file) {
      gt::gtsave(getBenchmarkDrugUtilisationTable(), file)
    }
  )
}
